_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "pretrained_backbone/vitaev2_s_convert.pth"

DATASETS:
  TRAIN: ("syntext1","syntext2","totaltext_train","mlt","ic13_train","ic15_train","textocr1","textocr2")
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-4
  WARMUP_ITERS: 0
  STEPS: (375000,)
  MAX_ITER: 435000
  CHECKPOINT_PERIOD: 100000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/pretrain"